
require('keymaps')
require('plugins.lazy')
require('plugins.misc')
require('plugins.gitsigns')
require('plugins.lualine')
require('options')
require('misc')
require('plugins.telescope')
require('plugins.treesitter')
require('plugins.lsp')
require('plugins.lspconfig')
require('plugins.trouble')
-- require('plugins.obsidian')
require('plugins.neogit')
require('layouts')
require('theme')
